name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [ build ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: |
        ./build.sh
        mv build _site

    - name: Fix permissions
      run: |
        chmod -v -R +rX "_site/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
