name: Build and deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      env:
        ANSIBLE_SSH_KEY: ${{ secrets.ANSIBLE_SSH_KEY }}
	ANSIBLE_BECOME_PASS: ${{ secrets.ANSIBLE_BECOME_PASS }}
      run: |
        ./build.sh
